import { Layout, SlideLayout } from "@/types/presentation";

export const DEFAULT_LAYOUTS: Record<string, Layout> = {
  "title-content": {
    _id: "title-content",
    name: "Title and Content",
    description: "A classic layout with a title and content area",
    type: SlideLayout.TITLE_CONTENT,
    elements: [
      {
        type: "title",
        x: 40,
        y: 40,
        width: 880,
        height: 80,
        fontSize: 36,
        textAlign: "left",
        placeholder: "Click to add title",
        value: "",
      },
      {
        type: "content",
        x: 40,
        y: 140,
        width: 880,
        height: 400,
        fontSize: 24,
        textAlign: "left",
        placeholder: "Click to add content",
        value: "",
      },
    ],
    isDefault: true,
    isPublic: true,
  },
  "title-content-image": {
    _id: "title-content-image",
    name: "Title, Content and Image",
    description: "A layout with title, content and an image area",
    type: SlideLayout.TITLE_CONTENT_IMAGE,
    elements: [
      {
        type: "title",
        x: 40,
        y: 40,
        width: 880,
        height: 80,
        fontSize: 36,
        textAlign: "left",
        placeholder: "Click to add title",
        value: "",
      },
      {
        type: "content",
        x: 40,
        y: 140,
        width: 400,
        height: 400,
        fontSize: 24,
        textAlign: "left",
        placeholder: "Click to add content",
        value: "",
      },
      {
        type: "image",
        x: 480,
        y: 140,
        width: 440,
        height: 400,
        placeholder: "Click to add image",
        value: "",
      },
    ],
    isPublic: true,
  },
  "content-only": {
    _id: "content-only",
    name: "Content Only",
    description: "A clean layout with just content",
    type: SlideLayout.CONTENT_ONLY,
    elements: [
      {
        type: "content",
        x: 40,
        y: 40,
        width: 880,
        height: 480,
        fontSize: 24,
        textAlign: "left",
        placeholder: "Click to add content",
        value: "",
      },
    ],
    isPublic: true,
  },
  "image-left": {
    _id: "image-left",
    name: "Image Left",
    description: "Image on the left with content on the right",
    type: SlideLayout.IMAGE_LEFT,
    elements: [
      {
        type: "title",
        x: 40,
        y: 40,
        width: 880,
        height: 80,
        fontSize: 36,
        textAlign: "left",
        placeholder: "Click to add title",
        value: "",
      },
      {
        type: "image",
        x: 40,
        y: 140,
        width: 400,
        height: 400,
        placeholder: "Click to add image",
        value: "",
      },
      {
        type: "content",
        x: 480,
        y: 140,
        width: 440,
        height: 400,
        fontSize: 24,
        textAlign: "left",
        placeholder: "Click to add content",
        value: "",
      },
    ],
    isPublic: true,
  },
  "image-right": {
    _id: "image-right",
    name: "Image Right",
    description: "Content on the left with image on the right",
    type: SlideLayout.IMAGE_RIGHT,
    elements: [
      {
        type: "title",
        x: 40,
        y: 40,
        width: 880,
        height: 80,
        fontSize: 36,
        textAlign: "left",
        placeholder: "Click to add title",
        value: "",
      },
      {
        type: "content",
        x: 40,
        y: 140,
        width: 400,
        height: 400,
        fontSize: 24,
        textAlign: "left",
        placeholder: "Click to add content",
        value: "",
      },
      {
        type: "image",
        x: 480,
        y: 140,
        width: 440,
        height: 400,
        placeholder: "Click to add image",
        value: "",
      },
    ],
    isPublic: true,
  },
  "two-column": {
    _id: "two-column",
    name: "Two Columns",
    description: "Equal width columns for content comparison",
    type: SlideLayout.TWO_COLUMN,
    elements: [
      {
        type: "title",
        x: 40,
        y: 40,
        width: 880,
        height: 80,
        fontSize: 36,
        textAlign: "center",
        placeholder: "Click to add title",
        value: "",
      },
      {
        type: "content",
        _id: "left-content",
        x: 40,
        y: 140,
        width: 420,
        height: 400,
        fontSize: 24,
        textAlign: "left",
        placeholder: "Left column content",
        value: "",
      },
      {
        type: "content",
        _id: "right-content",
        x: 500,
        y: 140,
        width: 420,
        height: 400,
        fontSize: 24,
        textAlign: "left",
        placeholder: "Right column content",
        value: "",
      },
    ],
    isPublic: true,
  },
  "full-image": {
    _id: "full-image",
    name: "Full Image",
    description: "Full slide image with optional title overlay",
    type: SlideLayout.FULL_IMAGE,
    elements: [
      {
        type: "image",
        x: 0,
        y: 0,
        width: 960,
        height: 540,
        placeholder: "Click to add image",
        value: "",
      },
      {
        type: "title",
        x: 40,
        y: 40,
        width: 880,
        height: 80,
        fontSize: 36,
        textAlign: "center",
        placeholder: "Click to add title",
        value: "",
      },
    ],
    isPublic: true,
  },
};
