import { Layout, SlideLayout } from "@/types/presentation";

export const DEFAULT_LAYOUTS: Record<string, Layout> = {
  "title-content": {
    _id: "title-content",
    name: "Title and Content",
    description: "A classic layout with a title and content area",
    type: SlideLayout.TITLE_CONTENT,
    elements: [
      {
        type: "title",
        x: 50,
        y: 50,
        width: 840,
        height: 100,
        fontSize: 36,
        textAlign: "left",
        placeholder: "Click to add title",
        value: "",
      },
      {
        type: "content",
        x: 50,
        y: 150,
        width: 840,
        height: 350,
        fontSize: 24,
        textAlign: "left",
        placeholder: "Click to add content",
        value: "",
      },
    ],
    isDefault: true,
    isPublic: true,
  },
  "title-content-image": {
    _id: "title-content-image",
    name: "Title, Content and Image",
    description: "A layout with title, content and an image area",
    type: SlideLayout.TITLE_CONTENT_IMAGE,
    elements: [
      {
        type: "title",
        x: 50,
        y: 30,
        width: 840,
        height: 100,
        fontSize: 36,
        textAlign: "left",
        placeholder: "Click to add title",
        value: "",
      },
      {
        type: "content",
        x: 50,
        y: 130,
        width: 840,
        height: 220,
        fontSize: 24,
        textAlign: "left",
        placeholder: "Click to add content",
        value: "",
      },
      {
        type: "image",
        x: 380,
        y: 350,
        width: 200,
        height: 200,
        placeholder: "Click to add image",
        value: "",
      },
    ],
    isPublic: true,
  },
  "content-only": {
    _id: "content-only",
    name: "Content Only",
    description: "A clean layout with just content",
    type: SlideLayout.CONTENT_ONLY,
    elements: [
      {
        type: "content",
        x: 50,
        y: 50,
        width: 840,
        height: 450,
        fontSize: 24,
        textAlign: "left",
        placeholder: "Click to add content",
        value: "",
      },
    ],
    isPublic: true,
  },
  "image-left": {
    _id: "image-left",
    name: "Image Left",
    description: "Image on the left with content on the right",
    type: SlideLayout.IMAGE_LEFT,
    elements: [
      {
        type: "title",
        x: 50,
        y: 50,
        width: 840,
        height: 100,
        fontSize: 36,
        textAlign: "left",
        placeholder: "Click to add title",
        value: "",
      },
      {
        type: "content",
        x: 420,
        y: 150,
        width: 500,
        height: 350,
        fontSize: 24,
        textAlign: "left",
        placeholder: "Click to add content",
        value: "",
      },
      {
        type: "image",
        x: 0,
        y: 150,
        width: 400,
        height: 350,
        placeholder: "Click to add image",
        value: "",
      },
    ],
    isPublic: true,
  },
  "image-right": {
    _id: "image-right",
    name: "Image Right",
    description: "Content on the left with image on the right",
    type: SlideLayout.IMAGE_RIGHT,
    elements: [
      {
        type: "title",
        x: 50,
        y: 50,
        width: 840,
        height: 100,
        fontSize: 36,
        textAlign: "left",
        placeholder: "Click to add title",
        value: "",
      },
      {
        type: "content",
        x: 20,
        y: 150,
        width: 400,
        height: 350,
        fontSize: 24,
        textAlign: "left",
        placeholder: "Click to add content",
        value: "",
      },
      {
        type: "image",
        x: 444,
        y: 150,
        width: 500,
        height: 350,
        placeholder: "Click to add image",
        value: "",
      },
    ],
    isPublic: true,
  },
  "full-image": {
    _id: "full-image",
    name: "Full Image",
    description: "Full slide image with optional title overlay",
    type: SlideLayout.FULL_IMAGE,
    elements: [
      {
        type: "title",
        x: 50,
        y: 50,
        width: 840,
        height: 100,
        fontSize: 36,
        textAlign: "center",
        placeholder: "Click to add title",
        value: "",
      },
      {
        type: "image",
        x: 50,
        y: 150,
        width: 840,
        height: 350,
        placeholder: "Click to add image",
        value: "",
      },
    ],
    isPublic: true,
  },
};
